language: node_js
node_js:
  - 10
notifications:
    slack: cs4920-2018:SDt3tqEvra7QvkVy5wnY9faR
install:
  - cd frontend
  - npm install
  - cd ../backend
  - npm install
script: 
  - cd frontend
  - npm test
  - cd ../backend
  - npm test