language: node_js
node_js:
  - 10
notifications:
    slack: cs4920-2018:SDt3tqEvra7QvkVy5wnY9faR
install:
  - cd frontend
  - npm install
  - npm run build
  - cd ../backend
  - npm install
script: 
  - npm test
  - cd ../frontend
  - npm test
after_script:
  - cd ../backend
  - npm run coverage
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: deploy-dev
      script:
        - cd ../
        - ./deploy.sh staging
    - stage: deploy-prod
      script:
        - cd ../
        - ./deploy.sh prod

stages:
  - name: deploy-prod
    if: branch = master
