language: node_js
node_js:
  - 10
notifications:
    slack: cs4920-2018:SDt3tqEvra7QvkVy5wnY9faR
install:
  - cd frontend
  - npm install
  - npm run build
  - cd ../backend
  - npm install
script: 
  - npm test
  - cd ../frontend
  - npm test
after_script:
  - cd ../backend
  - npm run coverage
cache:
  directories:
    - node_modules
deploy:
  provider: azure_web_apps
  site: smartcourse-test
  on: s5-deployment
  script:
    - cd ../
    - ./deploy.sh
