branch-defaults:
  default:
    environment: smartcourse-staging
    group_suffix: null
global:
  application_name: smartcourse
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
